trigger:
  - master

stages:
  # To deploy from local machine:
  # You need to have a recent verion of Azure CLI
  # az login --tenant deloitte.dk --use-device-code
  # Log in with your administrator account (The --use-device-code parameter allows you to choose a browser where you are logged in as the correct user instead of opening your default browser)
  # az account set --subscription "DK FACT - Microsoft Azure Enterprise (OS_EFF_BO)"
  # az deployment group create -g WorkoutBuddy-dev -f iac/deloitteWorkoutBuddyEnvironmentResources.bicep -p deploymentEnvironment=dev
  - stage: DeployStaging
    jobs:
      - deployment: DeployWorkoutBuddyEnvironmentInfrastructureToAzureDev
        environment: workout-buddy-staging
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - download: none
                - task: AzureCLI@2
                  displayName: Deploy
                  inputs:
                    azureSubscription: Azure subscription 1
                    scriptType: pscore
                    scriptLocation: inlineScript
                    inlineScript: |
                      az deployment group create `
                        --resource-group workout-buddy-staging-we `
                        --template-file $(Build.SourcesDirectory)/iac/main-resources.bicep `
                        --parameters deploymentEnvironment=staging

  - stage: DeployProd
    jobs:
      - deployment: DeployWorkoutBuddyEnvironmentInfrastructureToAzureProd
        environment: workout-buddy-prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - download: none
                - task: AzureCLI@2
                  displayName: Deploy
                  inputs:
                    azureSubscription: Azure subscription 1
                    scriptType: pscore
                    scriptLocation: inlineScript
                    inlineScript: |
                      az deployment group create `
                        --resource-group workout-buddy-prod `
                        --template-file $(Build.SourcesDirectory)/iac/main-resources.bicep `
                        --parameters deploymentEnvironment=prod
