name: Deploy Website

on:
  push:
    paths: app/
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-workoutbuddy-staging-we
  WEBAPP_BUILD_PATH: ${{ github.workspace }}/app/dist # vite's default build path is in 'dist' folder
  WEBAPP_DEPLOY_PATH: deploy/web
  NODE_VERSION: "20"
  VITE_FIREBASE_API_KEY: AIzaSyDUkptqktgTsyaEbjjlNKYD4g7jsW20Y98
  VITE_FIREBASE_APP_ID: 1:217070469792:web:1fb9f4e643b45d1f5f7fc5
  VITE_FIREBASE_PROJECT_ID: workout-buddy-bc830

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ github.workspace }}/app/package-lock.json

      - name: npm install, build, and test
        run: |
          npm --prefix ${{ github.workspace }}/app install
          npm --prefix ${{ github.workspace }}/app run build --if-present
          npm --prefix ${{ github.workspace }}/app run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ${{env.WEBAPP_BUILD_PATH}}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: ${{env.WEBAPP_DEPLOY_PATH}}

      - name: "Deploy to Azure WebApp"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.WEBAPP_DEPLOY_PATH}}
