name: Build and Deploy Web Api

env:
  AZURE_WEBAPP_NAME: app-workoutbuddy-staging-we
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  DOTNET_VERSION: "8"

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: dotnet build ./src/WorkoutBuddy.sln --configuration Release

      - name: Publish
        run: dotnet publish ./src/WorkoutBuddy/WorkoutBuddy.csproj -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

      - name: Debug Publish Output
        run: ls -la ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-api
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dotnet-api
          path: ./deploy

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy
