name: Deploy Web Api

env:
  AZURE_WEBAPP_NAME: app-workoutbuddy-staging-we
  WEBAPP_PUBLISH_PATH: ./publish
  WEBAPP_DEPLOY_PATH: ./deploy
  DOTNET_VERSION: "8"

  # workflow should trigger on push to master, pr into master, and if ran manually
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  #-------------------------------------------------------------------
  #
  # Build, test, publish Api and upload artifact
  #
  #-------------------------------------------------------------------
  build-job:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Dependency cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: dotnet build ./src/WorkoutBuddy.sln --configuration Release

      - name: Test
        run: dotnet test ./src/WorkoutBuddy.sln --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ./src/WorkoutBuddy/WorkoutBuddy.csproj -c Release -o ${{env.WEBAPP_PUBLISH_PATH}}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-api
          path: ${{env.WEBAPP_PUBLISH_PATH}}

  #-------------------------------------------------------------------
  #
  # Deploy artifact from build step to Azure Staging environment
  #
  #-------------------------------------------------------------------
  deploy-staging-job:
    name: Deploy Staging
    if: github.event_name == 'push' # Only deploy on push, not on pull requests
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-job
    environment:
      name: "WorkoutBuddyStaging"
      url: ${{ steps.deploy-staging.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-api
          path: ${{env.WEBAPP_DEPLOY_PATH}}

      - name: Deploy to Azure
        id: deploy-staging
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.WEBAPP_DEPLOY_PATH}}

  #-------------------------------------------------------------------
  #
  # Deploy artifact from build step to Azure Production environment
  #
  #-------------------------------------------------------------------
  deploy-prod-job:
    name: Deploy Production
    if: github.event_name == 'push' # Only deploy on push, not on pull requests
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [build-job, deploy-staging-job]
    environment:
      name: "WorkoutBuddyProduction"
      # url: ${{ steps.deploy-prod.outputs.webapp-url }} missing deploy to prod step

    steps:
      - name: TODO NOT IMPLEMENTED
        run: echo TODO NOT IMPLEMENTED
